-- MySQL Script generated by MySQL Workbench
-- Fri Jun 16 18:07:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TecWebDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TecWebDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TecWebDB` DEFAULT CHARACTER SET utf8 ;
USE `TecWebDB` ;

-- -----------------------------------------------------
-- Table `TecWebDB`.`Utenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TecWebDB`.`Utenti` (
  `username` VARCHAR(40) NOT NULL,
  `emailUtente` VARCHAR(45) NOT NULL,
  `passwordUtente` VARCHAR(65) NOT NULL,
  `bio` VARCHAR(200) NULL,
  `imgProfilo` BLOB NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `nomeUtente_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TecWebDB`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TecWebDB`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `descrizione` VARCHAR(3000) NULL,
  `autore` VARCHAR(40) NOT NULL,
  `dataOra` DATETIME NOT NULL,
  INDEX `fk_Post_Utenti1_idx` (`autore` ASC) ,
  PRIMARY KEY (`idPost`),
  CONSTRAINT `fk_Post_Utenti1`
    FOREIGN KEY (`autore`)
    REFERENCES `TecWebDB`.`Utenti` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TecWebDB`.`Files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TecWebDB`.`Files` (
  `idFiles` INT NOT NULL AUTO_INCREMENT,
  `imgBinary` BLOB NOT NULL,
  `idPost` INT NOT NULL,
  PRIMARY KEY (`idFiles`),
  UNIQUE INDEX `idFiles_UNIQUE` (`idFiles` ASC) ,
  INDEX `fk_Files_Post1_idx` (`idPost` ASC) ,
  CONSTRAINT `fk_Files_Post1`
    FOREIGN KEY (`idPost`)
    REFERENCES `TecWebDB`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TecWebDB`.`Segue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TecWebDB`.`Segue` (
  `utenteSeguente` VARCHAR(40) NOT NULL,
  `utenteSeguito` VARCHAR(40) NOT NULL,
  `dataOra` DATETIME NOT NULL,
  PRIMARY KEY (`utenteSeguente`, `utenteSeguito`),
  INDEX `fk_Utenti_has_Utenti_Utenti2_idx` (`utenteSeguito` ASC) ,
  INDEX `fk_Utenti_has_Utenti_Utenti1_idx` (`utenteSeguente` ASC) ,
  CONSTRAINT `fk_Utenti_has_Utenti_Utenti1`
    FOREIGN KEY (`utenteSeguente`)
    REFERENCES `TecWebDB`.`Utenti` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utenti_has_Utenti_Utenti2`
    FOREIGN KEY (`utenteSeguito`)
    REFERENCES `TecWebDB`.`Utenti` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TecWebDB`.`Mette_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TecWebDB`.`Mette_like` (
  `idLike` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) NOT NULL,
  `idPost` INT NOT NULL,
  `dataOra` DATETIME NOT NULL,
  INDEX `fk_Utenti_has_Post_Post1_idx` (`idPost` ASC) ,
  INDEX `fk_Utenti_has_Post_Utenti1_idx` (`username` ASC) ,
  PRIMARY KEY (`idLike`, `username`, `idPost`),
  CONSTRAINT `fk_Utenti_has_Post_Utenti1`
    FOREIGN KEY (`username`)
    REFERENCES `TecWebDB`.`Utenti` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utenti_has_Post_Post1`
    FOREIGN KEY (`idPost`)
    REFERENCES `TecWebDB`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TecWebDB`.`Commenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TecWebDB`.`Commenta` (
  `idCommento` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) NOT NULL,
  `idPost` INT NOT NULL,
  `dataOra` DATETIME NOT NULL,
  `commento` VARCHAR(300) NULL,
  INDEX `fk_Utenti_has_Post_Post2_idx` (`idPost` ASC) ,
  INDEX `fk_Utenti_has_Post_Utenti2_idx` (`username` ASC) ,
  UNIQUE INDEX `idCommento_UNIQUE` (`idCommento` ASC) ,
  PRIMARY KEY (`idCommento`),
  CONSTRAINT `fk_Utenti_has_Post_Utenti2`
    FOREIGN KEY (`username`)
    REFERENCES `TecWebDB`.`Utenti` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utenti_has_Post_Post2`
    FOREIGN KEY (`idPost`)
    REFERENCES `TecWebDB`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TecWebDB`.`Notifiche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TecWebDB`.`Notifiche` (
  `idNotifiche` INT NOT NULL AUTO_INCREMENT,
  `notifica` VARCHAR(200) NOT NULL,
  `dataOra` DATETIME NOT NULL,
  `username` VARCHAR(40) NOT NULL,
  `userNotifica` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idNotifiche`),
  INDEX `fk_Notifiche_Utenti1_idx` (`username` ASC) ,
  CONSTRAINT `fk_Notifiche_Utenti1`
    FOREIGN KEY (`username`)
    REFERENCES `TecWebDB`.`Utenti` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
